/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts -c wrangler.jsonc --include-runtime false` (hash: a5044163139df9ef497e04192e3da7b6)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	BETTER_AUTH_SECRET: string;
	SUPER_ADMIN_SIGNUP_PASSWORD: string;
	SITE_URL: string;
	TRUSTED_ORIGINS: string;
	Assistant: DurableObjectNamespace<import("./app/server").Assistant>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./app/server");
		durableNamespaces: "Assistant";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "BETTER_AUTH_SECRET"
				| "SUPER_ADMIN_SIGNUP_PASSWORD"
				| "SITE_URL"
				| "TRUSTED_ORIGINS"
			>
		> {}
}
