/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts -c wrangler.jsonc --include-runtime false` (hash: 5105a1cc5551e9383c7edbabf6faa45e)
declare namespace Cloudflare {
	interface Env {
		LOADER: WorkerLoader;
		DB: D1Database;
		BETTER_AUTH_SECRET: string;
		SITE_URL?: string;
		SUPER_ADMIN_SIGNUP_PASSWORD?: string;
		TRUSTED_ORIGINS?: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "BETTER_AUTH_SECRET"
				| "SITE_URL"
				| "SUPER_ADMIN_SIGNUP_PASSWORD"
				| "TRUSTED_ORIGINS"
			>
		> {}
}
